name: Releasing
on:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    name: Release Application
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Test application
        run: go test ./...
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Release application to Github
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: ~> v2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to npm
        uses: evg4b/goreleaser-npm-publisher-action@v1
        with:
          prefix: '@patrickdappollonio'
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          description: "Perform DNS lookups, WHOIS queries, connectivity testing, TLS certificate analysis, HTTP endpoint monitoring, and hostname resolution, all from your trusty AI."
          files: |-
            LICENSE
            README.md
          keywords: |-
            mcp
            mcp-server-debug
            debug-http-headers
            debug-dns-requests
            debug-tls-certificates
            http
            https
            cli
            devtool
